### PR TITLE
Windows toolchain Attempt 2

### PR DESCRIPTION
**Pull request by networkfusion**
This PR is based on the latest trunk and excludes the fat... although might suffer from missing changes.

### CODE REVIEW

**Comment by networkfusion** [comment]
The only (valid) change for this PR would be commit `[9c887c8]`. Although the makefile changes should (possibily) be split out, they are useful for tests to ensure a valid (matching) ROM.

**Comment by rasky** [comment]
This is still missing the CI YML updates right? Right now it doesn't build the Canadian cross toolchain.

**Comment by networkfusion** [comment]
I have just updated the necessary part of the CI, but still might have missed something...

**Comment by networkfusion** [comment]
There is still something amiss that is solved in https://github.com/N64-tools/mips64-gcc-toolchain. I have yet to get to the bottom of it... but would welcome a review of the compiler options used (to both concentrate efforts and "optimize" output size).

**Comment by rasky** [comment]
Thanks, submitted as https://github.com/DragonMinded/libdragon/pull/306

**Pull request closed without merging**
